version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/static
    ports:
      - "8123:8123"
    environment:
      DB_PSQL_HOST: db
      DB_PSQL_NAME: casa_v_db
      DB_PSQL_USER: casa_v_admin
      DB_PSQL_PASSWORD: casa_v_password
      DB_PSQL_PORT: "5432"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: casa_v_db
      POSTGRES_USER: casa_v_admin
      POSTGRES_PASSWORD: casa_v_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media:
  static:
